# -*- coding: utf-8 -*-
"""Car_Identifier_Voila.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_SwRA0VUkga3zoCsnBIEQv2ExiM3D9H0
"""



from fastai.vision import *
from fastbook import *
import gradio as gr

"""# What maker is this car?
Ahmed is a secondary school student in Lagos. He needs to get a side job to support his single mom and little sister. He got a job as a survey assistant. His first task is to find out if some set of pictures contain Mercedes or Honda cars. Cool, right?


But Ahmed can barely identify all the hundreds of models these car giants have released over the years. He definitely needs someone who can identify any Honda or Mercedes from any angle or he's going to be turning in unreliable reports to his supervisor. And NO!, he can't share his wage with anyone. 


What's the way out? 


## THE MERCEDES-HONDA IDENTIFIER! 

Ahmed got an intelligent friend who is more efficient at knowing Mercedes and Honda cars, no matter their posture. Not only that, his new friend doesn't need money.

Test Ahmed's new intelligent friend and see how intelligent his friend is!
"""



learner_inf = load_learner('car_model_identifier.pkl')



def classify_image(file):
#  image = PILImage.create(file)
  categories = ('Honda', 'Mercedes')
  pred, pred_idx, probs = learner_inf.predict(file)
  result = dict(zip(categories, map(float,probs)))
  return result

app = gr.Interface(
    fn = classify_image,
    inputs = gr.Image(),
    outputs= gr.Label(),
    examples = ['download (1).png', 'download (2).png', 'download (4).png', 'images (41).png', 'images - 2022-12-07T052510.177.png', 'images - 2022-12-07T052511.014.png', 'images - 2022-12-07T053716.324.png', 'images - 2022-12-07T053818.478.png', 'images - 2022-12-07T053820.398.png']
)

app.launch()

